jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
      includePreviewVersions: true
  - script: dotnet restore
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '*/*.csproj'
      arguments: '--configuration Release'
- job: Ubuntu
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
      includePreviewVersions: true
  - script: dotnet restore
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '*/*.csproj'
      arguments: '--configuration Release'
