jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
      includePreviewVersions: true
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    displayName: PublishDotNet
    inputs:
      command: publish
      projects: 'website-downloader'
      publishWebProjects: false
      modifyOutputPath: false
      arguments: '--configuration Release --self-contained --runtime win-x64 --output $(Build.ArtifactStagingDirectory)/website-downloader-win-x64'
  - task: PublishBuildArtifacts@1
    displayName: PublishArtifacts
- job: Ubuntu
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
      includePreviewVersions: true
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    displayName: PublishDotNet
    inputs:
      command: publish
      projects: 'website-downloader'
      publishWebProjects: false
      modifyOutputPath: false
      arguments: '--configuration Release --self-contained --runtime linux-x64 --output $(Build.ArtifactStagingDirectory)/website-downloader-linux-x64'
  - task: PublishBuildArtifacts@1
    displayName: PublishArtifacts
